### ISSUE TITLE
Error: Cannot find module 'xtend'

### ISSUE THREAD

**Issue by jayfallon** [zemirco/lockit#1]
I've tried to get the example app up and running but keep getting the following message:

`Error: Cannot find module 'xtend'`

Node v0.10.24
NPM v1.3.21
grunt-cli v0.1.11

Thanks.

**Comment by MrHyacinth** [comment]
this answer seems to be tailored for those who cloned the repository. I'm currently trying to start a new react-native project and i'm encountering the same error after running "react-native init <projectname>. Somebody help!!!
