### ISSUE TITLE
Why is there no unique index on username and email address?

### ISSUE THREAD

**Issue by valnub** [zemirco/lockit#37]
I noticed on my mongodb installation for lockit that an index is set for user's id. That's good. However, lockit does not seem to set an unique index for username and email address which it should in my opinion or is there a specific reason not to do so?

**Comment by zemirco** [comment]
Can you open a pull request?

**Comment by valnub** [comment]
Sure

**Comment by zemirco** [comment]
Any progress?

**Comment by valnub** [comment]
I'm very busy right now but I have that on my list for Aug. 2nd if that's not to late ;-)

**Comment by valnub** [comment]
I tried to send my pull request to `lockit-mongodb-adapter` but I only get this:

![bildschirmfoto 2015-07-25 um 18 16 21](https://cloud.githubusercontent.com/assets/3787662/8890252/4fd338d2-32f9-11e5-88fc-09af4f007721.png)

Could it be that you need grant me rights?

**Comment by zemirco** [comment]
you need to create your own fork and push changes to it. then send a pull request.

**Comment by valnub** [comment]
Got it to work: https://github.com/zemirco/lockit-mongodb-adapter/pull/4
