### ISSUE TITLE
how do i know who i am in client (browser side)?

### ISSUE THREAD

**Issue by jzkunlun** [zemirco/lockit#40]
Is there any method I can call to return who i am logged in on browser side? I need this information to pass to different form on the page.

**Comment by zemirco** [comment]
Is your page a single page application or do you use server side rendered pages?

In case you have a single page app with some kind of JavaScript framework you can query [/whoami](https://github.com/zemirco/lockit/blob/master/examples/angular/app.js#L41-L45)

``` js
app.get('/rest/whoami', utils.restrict(config), function(req, res) {
  res.json({
    name: req.session.name
  });
});
```

In case you have server side rendered pages you have access to username and email via the [session object](https://github.com/zemirco/lockit-login/blob/master/index.js#L260-L261).

``` js
req.session.name = updatedUser.name;
req.session.email = updatedUser.email;
```

Use those as local variable similar to the gravatar example.

``` js
res.render('gravatar', {
  name: usr.name,
  gravatar: url
});
```

**Comment by jzkunlun** [comment]
thanks,
