### ISSUE TITLE
Why did you make GET /logout?

### ISSUE THREAD

**Issue by kulakowka** [zemirco/lockit#42]
Explain me please why did you make logout using `GET /logout`?

It's not safe. Anyone can insert a picture `<img src="http://yousite.com/logout" />` and your users will logged out.

It may be better to do `POST /logout`?

How do I change this in the `config.js`?

**Comment by zemirco** [comment]
Because I didn't know better at this time. See my latest tweet - https://twitter.com/zemirco/status/660802777879355392.

It cannot be changed via `config.js`. If you like, edit the code and send a pull request. No time at the moment to make the changes myself.
