### ISSUE TITLE
Waterline adapter

### ISSUE THREAD

**Issue by nmcclay** [zemirco/lockit#5]
This is pretty neat, however the way the DB configurations are currently setup I found it quite tricky to make it work with my Sails.js site using the Waterline ORM.  Basically I could bypass the ORM to connect directly separately to Mongo or Postgres or whatever the ORM adapter in waterline is pointed to as well.  But I'd much prefer a lockit waterline adapter and just let the ORM to deal with those details.

Just a thought,

**Comment by zemirco** [comment]
Looks like Sails.js is still using Express 3.x. Lockit is built for Express 4.x. Until Sails.js doesn't upgrade Express, lockit+sails probably won't work.
